language: rust

rust:
  - stable

services:
    # For the musl-based release build:
  - docker

env:
    # If there are any panics during a unit test, print the entire
    # backtrace.
  - RUST_BACKTRACE=1

cache:
  directories:
      # This caches downloaded source code but not compiled binaries,
      # which is probably what we want.
    - $HOME/.cargo

script:
  - cargo test

before_deploy:
    # Download a musl-based toolchain to get a static binary
  - docker pull andrewd/rust-musl
    # Create an optimized release build
  - >
    docker run -v $PWD:/build andrewd/rust-musl /bin/sh -c
    'cd /build; cargo build --target x86_64-unknown-linux-musl --release'
